POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbnJpayIsImlkIjoiNWJmZmExNWQ0YzY0MWEzZGJiMmE1NzNkIiwiaWF0IjoxNTQzNDkzNTQ4fQ.kbGbAyKUBFgRg0Re-A4-sNWO44JalFxjjsgyrNwZQmk

{
  "title": "AB metsäkeskus",
  "author": "AB Suomen metsäkeskus",
  "url": "https://www.metsakeskus.fi/blogi",
  "likes": 74
}