PUT http://localhost:3003/api/blogs/5c004647ed20b84274893771
content-type: application/json

{
  "title": "Type wars red",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": 4
}